parameters:
#    touq_Gallery.example.class: Touq\GalleryBundle\Example

services:
#    touq_Gallery.example:
#        class: %touq_Gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
