parameters:
#    touq_galery.example.class: Touq\GaleryBundle\Example

services:
#    touq_galery.example:
#        class: %touq_galery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
