parameters:
#    touq_inventory.example.class: Touq\InventoryBundle\Example

services:
#    touq_inventory.example:
#        class: %touq_inventory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
